/**
 * Weekly newsletter content — AI 整理的 ESG / SDG 重點 附 Brand Capital 解讀
 *
 * Each entry is one weekly issue. To add a new issue, append to NEWS_ENTRIES
 * with a unique slug (use ISO date prefix, e.g. "2026-w22-..."), set
 * `publishedAt` and `sections`, and commit. The list page and detail page
 * pick it up automatically.
 *
 * Future: this file can be generated by an automation that pulls from Notion
 * (docs/notion-sync) and re-commits weekly. Keep the schema stable for that.
 */

export type NewsCategory = "ESG" | "SDG" | "AI 治理" | "品牌資本";

export interface NewsSection {
  /** Section heading shown on the article page. */
  heading: string;
  /** 1-3 short paragraphs. Plain text; no HTML. */
  body: string[];
  /** Optional source links — title + URL. Shown as footnotes. */
  sources?: { title: string; url: string }[];
}

export interface NewsEntry {
  /** URL slug, must be unique. ISO-week prefix recommended. */
  slug: string;
  /** ISO date, e.g. "2026-05-27". */
  publishedAt: string;
  /** Display title. */
  title: string;
  /** 1-2 sentence summary shown on list view + meta description. */
  summary: string;
  /** Category badges, first one is primary. */
  categories: NewsCategory[];
  /** The article body, structured into sections. */
  sections: NewsSection[];
  /** Brand Capital 解讀 — Symcio 的觀點段落,獨立於正文。 */
  brandCapitalTake: string[];
}

export const NEWS_ENTRIES: NewsEntry[] = [
  {
    slug: "2026-w22-esg-sdg-ai-governance",
    publishedAt: "2026-05-27",
    title: "ESG/SDG 本週重點：AI 治理被納入永續報告書,品牌資本三軸首次對齊",
    summary:
      "歐盟 CSRD 第二輪揭露涵蓋 AI 治理風險,SBTi 把生成式 AI 耗能納入 Scope 3 範疇 3,SDG 9 與 SDG 12 同時被點名。對品牌資本的意涵:SCV(永續合規)與 AIV(AI 可見度)從此不能分開看。",
    categories: ["ESG", "AI 治理", "品牌資本"],
    sections: [
      {
        heading: "CSRD 第二輪:AI 治理進入強制揭露",
        body: [
          "歐盟企業永續報告指令(CSRD)2026 年起的第二批適用企業,需在 ESRS G1(治理)章節揭露生成式 AI 的使用範疇、內部審查機制與風險矩陣。這是首次將 AI 治理從「自願軟性揭露」拉進「強制硬性揭露」。",
          "對台灣供應鏈影響:出口至歐盟的上市櫃公司、以及為 CSRD 適用企業提供關鍵服務的第三方(含品牌代理、行銷科技、SaaS),都會被間接點名要求一致水準的揭露。",
        ],
        sources: [
          {
            title: "EFRAG · ESRS G1 Disclosure Requirements (working draft)",
            url: "https://www.efrag.org/lab6",
          },
        ],
      },
      {
        heading: "SBTi:生成式 AI 耗能納入 Scope 3 範疇 3 試算",
        body: [
          "Science Based Targets initiative(SBTi)5 月發布的草案,首次把企業使用第三方生成式 AI 服務(ChatGPT / Claude / Gemini 等)所引發的間接運算碳排,歸類為 Scope 3 範疇 3「採購商品與服務」。",
          "意涵:過去「用 AI 提升效率」被視為純正面敘事,現在必須附帶碳足跡揭露。對重度使用 AI 寫稿、客服、設計的品牌,等於多了一條年度報告書義務段落。",
        ],
      },
      {
        heading: "SDG 9 × SDG 12:創新基礎建設 vs. 負責任生產",
        body: [
          "本週聯合國 UN Global Compact 拉出兩個原本相對冷門的目標:SDG 9.5(強化科學研究、升級工業部門技術能力)與 SDG 12.6(鼓勵企業採用永續做法,並將永續資訊納入定期報告)。",
          "兩者交集處,正是「企業如何負責任地導入 AI」這件事——它既是 SDG 9 的創新採用,也是 SDG 12 的責任揭露。Symcio 觀察:這是未來三年 ESG 報告書最會被審計師加碼追問的章節。",
        ],
      },
    ],
    brandCapitalTake: [
      "BCI 三軸框架在本週同時被外部標準觸及:CSRD/ESRS 推動 SCV(永續合規價值)結構化、SBTi 把 AI 用量推進 Scope 3 從而連動 AIV(AI 可見度價值)的耗能成本曲線、FBV(財務品牌價值)則因為兩者的揭露要求而面臨重估壓力。",
      "對品牌主的具體行動建議:(1)盤點目前所有對外溝通中提到「AI-powered / AI-driven」的素材,確認對應的內控與揭露能撐住監管問詢;(2)把 AI 引擎曝光量化(Symcio ABVI)與 ESG 報告書的「責任 AI」章節同步準備,讓兩條敘事互為佐證;(3)避免把 ESG 與 AI 治理視為兩個部門的事——CSRD G1 章節已經要求一體揭露。",
      "Symcio 在 BCI 方法論裡,SCV 與 AIV 本來就設計成可獨立量測但同步追蹤的兩條時序——本週的監管動向證實這個設計方向是對的。",
    ],
  },
];

export function findEntry(slug: string): NewsEntry | undefined {
  return NEWS_ENTRIES.find((e) => e.slug === slug);
}

export function sortedEntries(): NewsEntry[] {
  return [...NEWS_ENTRIES].sort((a, b) =>
    a.publishedAt < b.publishedAt ? 1 : -1,
  );
}
